### ISSUE TITLE
Items are flat when dropped?

### ISSUE THREAD

**Issue by Bizzlerian** [MeeniMc/UltiCraft-Models3D#1]
Not really an issue, but how do I remove the effect where dropped items like swords and pickaxe's are 'flat' on the ground? (like when you drop your item with physic mod)

Is there a way to remove this? 

Thanks!

**Comment by MeeniMc** [comment]
Next release will remove  that behavior

**Comment by Bizzlerian** [comment]
> Next release will remove that behavior

Thank you! - I really do enjoy using this resource pack, so I’m very happy to hear this!

Thank you for your time and effort. 🙂
